name: Build and Trigger

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  NEXT_IN_CHAIN: "enhanceMaxMcMurray/open-suite-webapp"
  NEXT_IN_CHAIN_WORKFLOWID: "docker-image.yml" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install webapp
        run: git clone -b dev https://github.com/axelor/open-suite-webapp.git open-suite-webapp
      - name: move to the right place
        run: mkdir -p open-suite-webapp/modules/axelor-open-suite && ls | grep -v open-suite-webapp | xargs -I{} mv {} open-suite-webapp/modules/axelor-open-suite
      - name: Grant execute permission for gradlew
        run: chmod +x open-suite-webapp/gradlew
      - name: Check spotless format with gradle task
        run: cd open-suite-webapp && ./gradlew spotlessCheck
      - name: Check that CSV files use the correct CR/LF EOL char (\r\n)
        run: cd open-suite-webapp && ./gradlew checkCsvEOL
      - name: Check changelog generation with gradle task
        run: cd open-suite-webapp && ./gradlew generateChangelog
      - name: Build without tests
        run: cd open-suite-webapp && ./gradlew -xtest clean build
      - name: Run tests
        run: cd open-suite-webapp && ./gradlew test
      - name: trigger
        run: |
          curl -XPOST \
            -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ env.NEXT_IN_CHAIN }}/actions/workflows/${{ env.NEXT_IN_CHAIN_WORKFLOWID }}/dispatches \
            --data '{"ref":"master"}'
